# Generated by Django 4.1.7 on 2023-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("classid", models.IntegerField(primary_key=True, serialize=False)),
                ("classname", models.CharField(max_length=50)),
                ("classyear", models.CharField(max_length=10)),
                ("classgrade", models.CharField(default="A", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="grades_pdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="pdfs/")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("studentid", models.IntegerField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("dateofbirth", models.DateField()),
                ("dateofenrolment", models.DateField()),
                ("nationality", models.CharField(max_length=50)),
                ("dateofgraduation", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        related_name="students", to="dashboard.class"
                    ),
                ),
            ],
        ),
    ]
