# Generated by Django 4.1.7 on 2023-05-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_academicyear_score_year_delete_grades_pdf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="year",
        ),
    ]
