# Generated by Django 4.1.7 on 2023-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_score_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="academicyear",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
