# Generated by Django 4.2.1 on 2023-05-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_academicyear_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.year'),
        ),
    ]
