# Generated by Django 4.2.1 on 2023-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_class_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.IntegerField(
                choices=[
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                ]
            ),
        ),
    ]
