# Generated by Django 4.2.1 on 2023-05-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_year_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="score",
            old_name="student",
            new_name="studentid",
        ),
    ]
